---
builds:
  - id: shup
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    dir: .
    main: main.go
    binary: shup
    flags:
      - -trimpath
    ldflags: -s -w -X github.com/ai-shflow/shup/config.Build={{.Date}} -X github.com/ai-shflow/shup/config.Version={{.Version}}

changelog:
  sort: asc
  filters:
    exclude:
      - Merge pull request
      - Merge branch
